# only devguard is allowed to communicate with kratos
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kratos
  namespace: "{{ .Release.Namespace }}"
spec:
    podSelector:
        matchLabels:
        app.kubernetes.io/name: kratos
    policyTypes:
    - Ingress
    ingress:
    - from:
        - podSelector:
            matchLabels:
            app.kubernetes.io/name: devguard-api
      ports:
      - protocol: TCP
        port: 4434 # restrict access to the admin port