apiVersion: apps/v1
kind: Deployment
metadata:
  name: devguard-web-deployment
  labels:
    {{- include "devguard.labels" . | nindent 4 }}
    app: devguard-web
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: devguard-web
  template:
    metadata:
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "devguard.labels" . | nindent 8 }}
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: devguard-web
        version: {{ .Chart.AppVersion }}
    spec:
      {{- with .Values.web.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
          - name: ORY_KRATOS_URL
            value: http://kratos:4433
          - name: NEXT_PUBLIC_devguard_API_URL
            value: http://devguard-api-service:8080
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /api/v1/health
          #     port: http
          #   initialDelaySeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /api/v1/health
          #     port: http
          #   initialDelaySeconds: 10
          resources:
            limits:
              cpu: 4
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
