apiVersion: v1
kind: Service
metadata:
  name: flawfix-web-service
  labels:
    {{- include "flawfix.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flawfix-web
