version: '3.7'

# postgresql database for local development
services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
      - ./export:/export
  
  kratos-migrate:
    image: oryd/kratos:v1.0.0
    depends_on:
      - postgresql
    environment:
      - DSN=postgres://kratos:secret@postgresql:5432/kratos?sslmode=disable
    volumes:
      - type: bind
        source: ./.kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes


  hydra:
    image: oryd/hydra:v2.2.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./.hydra
        target: /etc/config/hydra
    environment:
      - DSN=postgres://hydra:secret@postgresql:5432/hydra?sslmode=disable
    depends_on:
      - hydra-migrate

  hydra-migrate:
    image: oryd/hydra:v2.2.0
    depends_on:
      - postgresql
    environment:
      - DSN=postgres://hydra:secret@postgresql:5432/hydra?sslmode=disable
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./.hydra
        target: /etc/config/hydra

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v2.2.0
    ports:
      - "3000:3000"
    restart: unless-stopped


  oathkeeper:
    image : oryd/oathkeeper:v0.40.7
    ports: 
      - "4455:4455"
    volumes:
        - type: bind
          source: ./.oathkeeper
          target: /etc/config/oathkeeper

  kratos:
    image: oryd/kratos:v1.0.0
    depends_on:
      - kratos-migrate
      - postgresql
    ports:
      - '4433:4433' # public
      # - '4434:4434' # admin
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    environment:
      - DSN=postgres://kratos:secret@postgresql:5432/kratos?sslmode=disable
      - LOG_LEVEL=trace
    volumes:
        - type: bind
          source: ./.kratos
          target: /etc/config/kratos
volumes:
  postgres:
