apiVersion: v1
kind: Service
metadata:
  name: flawfix-api-service
  labels:
    {{- include "flawfix.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flawfix-api
