# Default values for devguard.
# This is a YAML-formatted file.
# Declare variables to be passed into templates.
oidc:
  enabled: false
  github:
    enabled: false
    clientId:
    existingClientSecret: github-client-secret # needs to contain key "secret"

mail:
  # needs to contain key: "uri". Format should be like: smtps://<user>@<your-domain.com>:<secret>@<mail-server.de>:465/?skip_ssl_verify=false
  existingSMTPConnectionUriSecret:
  fromAddress: ""
api:
  replicaCount: 1
  image:
    repository: ghcr.io/l3montree-dev/devguard
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v1.0.0
  imagePullSecrets: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}

  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
    - host: example.com
      paths:
      - path: /
        pathType: Prefix

  github:
    appId: abc
    # needs to contain "webhookSecret"
    existingWebhookSecretSecretName: github-app-webhook-secret
    # needs to contain key "privateKey"
    existingPrivateKeySecretName: github-app-private-key
web:
  image:
    repository: ghcr.io/l3montree-dev/devguard-web
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v1.0.0
  imagePullSecrets: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}

  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
    - host: app.example.com
      paths:
      - path: /
        pathType: Prefix
