
{{- $protocol := "http" -}}
{{- if .Values.web.ingress.tls -}}
{{- $protocol = "https" -}}
{{- end -}}
{{- $host := index .Values.web.ingress.hosts 0 -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devguard-api-deployment
  labels:
    {{- include "devguard.labels" . | nindent 4 }}
    app: devguard-api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: devguard-api
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "devguard.labels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: devguard-api
        version: {{ .Chart.AppVersion }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
          - name: POSTGRES_DB
            value: devguard
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres-password
                name: db-secret
          - name: POSTGRES_USER
            value: devguard
          - name: POSTGRES_HOST
            value: postgresql
          - name: FRONTEND_URL
            value: {{ printf "%s://%s" $protocol $host.host }}
          - name: ORY_KRATOS_PUBLIC
            value: http://kratos:4433
          - name: ORY_KRATOS_ADMIN
            value: http://kratos:4434
          - name: GOMEMLIMIT
            value: 1024MiB
          - name: GITHUB_APP_ID
            value: {{ .Values.api.github.appId | quote }}
          - name: GITHUB_PRIVATE_KEY
            value: /github-app-private-key
          - name: GITHUB_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                key: webhookSecret
                name: {{ .Values.api.github.existingWebhookSecretSecretName }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 4
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 1024Mi
          volumeMounts:
          - mountPath: /github-app-private-key
            name: github-app-private-key
            subPath: privateKey
      volumes:
      - name: github-app-private-key
        secret:
          secretName: {{ .Values.api.github.existingPrivateKeySecretName }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
