name: VulnDB Workflow

on: workflow_dispatch

env:
  POSTGRES_DB: flawfix
  POSTGRES_USER: flawfix
  POSTGRES_HOST: localhost
  POSTGRES_PASSWORD: not_reachable_from_the_internet

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.3-alpine3.20@sha256:e89da2c083a5405943408b6807cd1fd25dc9010c1294e30611b841778bedc653
        env:
          POSTGRES_DB: flawfix
          POSTGRES_USER: flawfix
          POSTGRES_PASSWORD: not_reachable_from_the_internet
        ports:
        - 5432:5432
        options: "--health-cmd=\"pg_isready -U flawfix\"  --health-interval=10s  --health-timeout=5s  --health-retries=5 "
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Golang
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build the database (this takes some time)
      run: |
        go run ./cmd/flawfix-cli/main.go vulndb repair --startIndex=0

    - name: Install postgresql client
      run: |
        sudo apt-get update
        sudo apt-get install postgresql-client-16

    - name: Dump the PostgreSQL database
      # skip:checkov:CKV_SECRET_6
      run: PGPASSWORD=not_reachable_from_the_internet pg_dump -h localhost -U flawfix flawfix > dump.sql

    - name: Setup oras cli
      uses: oras-project/setup-oras@v1

    - name: Push the database dump to OCI
      run: |
        oras push ghcr.io/flawfix/dump:$(date +%s) dump.sql
